# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'modalsample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Charts'
  pod 'TinyConstraints'

  # Pods for modalsample
  target 'modalsampleTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Charts'
    pod 'TinyConstraints'
  end

  target 'modalsampleUITests' do
    # Pods for testing
    pod 'Charts'
    pod 'TinyConstraints'
  end

end
